"""
Question Paper Formatter
Converts JSON output to beautifully formatted question papers
"""
import json
from datetime import datetime
from typing import Dict, List, Any


class QuestionPaperFormatter:
    """Formats question paper JSON into readable documents"""
    
    def __init__(self):
        self.header_template = """
╔══════════════════════════════════════════════════════════════════════════════╗
║                         QUESTION PAPER                                        ║
║                    Generated by ScoriX AI System                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

Generated on: {date}
Time: {time}

"""
    
    def format_to_text(self, data: List[Any], course_name: str = "Course") -> str:
        """
        Format JSON data to readable text format
        
        Args:
            data: Question paper data (content_data, questions)
            course_name: Name of the course
            
        Returns:
            Formatted text string
        """
        output = []
        
        # Add header
        now = datetime.now()
        output.append(self.header_template.format(
            date=now.strftime("%B %d, %Y"),
            time=now.strftime("%I:%M %p")
        ))
        
        output.append(f"Course: {course_name}\n")
        output.append("="  * 80)
        output.append("\n")
        
        # Extract questions from data
        if isinstance(data, (list, tuple)) and len(data) == 2:
            content_data, questions = data
        else:
            questions = data if isinstance(data, list) else []
        
        # Format each CO section
        for idx, co_data in enumerate(questions, 1):
            if not isinstance(co_data, dict):
                continue
                
            co = co_data.get('CO', co_data.get('co', 'Unknown'))
            po = co_data.get('PO', co_data.get('po', []))
            topics = co_data.get('topics', [])
            co_questions = co_data.get('questions', [])
            
            # CO Header
            output.append(f"\n{'─' * 80}\n")
            output.append(f"COURSE OUTCOME {idx}\n")
            output.append(f"{'─' * 80}\n\n")
            output.append(f"CO{idx}: {co}\n\n")
            
            # Program Outcomes
            if po:
                output.append("Program Outcomes (PO):\n")
                if isinstance(po, list):
                    for po_item in po:
                        output.append(f"  • {po_item}\n")
                else:
                    output.append(f"  • {po}\n")
                output.append("\n")
            
            # Topics Covered
            if topics:
                output.append("Topics Covered:\n")
                for topic in topics:
                    output.append(f"  • {topic}\n")
                output.append("\n")
            
            # Questions
            if co_questions:
                output.append(f"QUESTIONS (Total: {len(co_questions)})\n")
                output.append(f"{'─' * 80}\n\n")
                
                for q_idx, question in enumerate(co_questions, 1):
                    output.append(f"Q{idx}.{q_idx}. {question}\n\n")
            
        # Footer
        output.append("\n" + "="  * 80)
        output.append("\n\nEND OF QUESTION PAPER\n")
        output.append("="  * 80)
        
        return ''.join(output)
    
    def format_to_html(self, data: List[Any], course_name: str = "Course") -> str:
        """
        Format JSON data to HTML format
        
        Args:
            data: Question paper data
            course_name: Name of the course
            
        Returns:
            HTML string
        """
        now = datetime.now()
        
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question Paper - {course_name}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap');
        
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 2rem;
        }}
        
        .container {{
            max-width: 900px;
            margin: 0 auto;
            background: white;
            padding: 3rem;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        }}
        
        .header {{
            text-align: center;
            border-bottom: 3px solid #667eea;
            padding-bottom: 2rem;
            margin-bottom: 2rem;
        }}
        
        .header h1 {{
            font-size: 2.5rem;
            font-weight: 700;
            background: linear-gradient(135deg, #667eea, #764ba2);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 0.5rem;
        }}
        
        .header .subtitle {{
            font-size: 1.1rem;
            color: #666;
            margin-bottom: 1rem;
        }}
        
        .meta {{
            display: flex;
            justify-content: space-between;
            font-size: 0.9rem;
            color: #888;
            margin-top: 1rem;
        }}
        
        .course-name {{
            font-size: 1.5rem;
            font-weight: 600;
            color: #333;
            margin-bottom: 2rem;
            padding: 1rem;
            background: linear-gradient(135deg, rgba(102, 126, 234, 0.1), rgba(118, 75, 162, 0.1));
            border-left: 4px solid #667eea;
            border-radius: 8px;
        }}
        
        .co-section {{
            margin-bottom: 3rem;
            page-break-inside: avoid;
        }}
        
        .co-header {{
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white;
            padding: 1rem 1.5rem;
            border-radius: 8px;
            margin-bottom: 1.5rem;
        }}
        
        .co-header h2 {{
            font-size: 1.3rem;
            font-weight: 600;
            margin-bottom: 0.5rem;
        }}
        
        .co-description {{
            font-size: 1rem;
            opacity: 0.95;
        }}
        
        .po-section, .topics-section {{
            background: #f8f9fa;
            padding: 1rem 1.5rem;
            border-radius: 8px;
            margin-bottom: 1.5rem;
        }}
        
        .po-section h3, .topics-section h3 {{
            font-size: 1.1rem;
            font-weight: 600;
            color: #667eea;
            margin-bottom: 0.75rem;
        }}
        
        .po-section ul, .topics-section ul {{
            list-style: none;
            padding-left: 0;
        }}
        
        .po-section li, .topics-section li {{
            padding: 0.5rem 0;
            padding-left: 1.5rem;
            position: relative;
        }}
        
        .po-section li:before, .topics-section li:before {{
            content: "▸";
            position: absolute;
            left: 0;
            color: #667eea;
            font-weight: bold;
        }}
        
        .questions-section {{
            margin-top: 1.5rem;
        }}
        
        .questions-header {{
            font-size: 1.2rem;
            font-weight: 600;
            color: #333;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid #e0e0e0;
        }}
        
        .question {{
            margin-bottom: 2rem;
            padding: 1.5rem;
            background: white;
            border: 1px solid #e0e0e0;
            border-left: 4px solid #667eea;
            border-radius: 8px;
            transition: all 0.3s ease;
        }}
        
        .question:hover {{
            box-shadow: 0 4px 12px rgba(102, 126, 234, 0.15);
            transform: translateX(4px);
        }}
        
        .question-number {{
            font-weight: 700;
            color: #667eea;
            margin-right: 0.5rem;
            font-size: 1.1rem;
        }}
        
        .question-text {{
            color: #333;
            font-size: 1rem;
            line-height: 1.8;
        }}
        
        .footer {{
            margin-top: 3rem;
            padding-top: 2rem;
            border-top: 2px solid #e0e0e0;
            text-align: center;
            color: #888;
            font-size: 0.9rem;
        }}
        
        @media print {{
            body {{
                background: white;
                padding: 0;
            }}
            
            .container {{
                box-shadow: none;
                padding: 1.5rem;
            }}
            
            .question:hover {{
                transform: none;
                box-shadow: none;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Question Paper</h1>
            <div class="subtitle">Generated by ScoriX AI System</div>
            <div class="meta">
                <span>Generated on: {now.strftime("%B %d, %Y")}</span>
                <span>Time: {now.strftime("%I:%M %p")}</span>
            </div>
        </div>
        
        <div class="course-name">
            📚 Course: {course_name}
        </div>
"""
        
        # Extract questions from data
        if isinstance(data, (list, tuple)) and len(data) == 2:
            content_data, questions = data
        else:
            questions = data if isinstance(data, list) else []
        
        # Format each CO section
        for idx, co_data in enumerate(questions, 1):
            if not isinstance(co_data, dict):
                continue
                
            co = co_data.get('CO', co_data.get('co', 'Unknown'))
            po = co_data.get('PO', co_data.get('po', []))
            topics = co_data.get('topics', [])
            co_questions = co_data.get('questions', [])
            
            html += f"""
        <div class="co-section">
            <div class="co-header">
                <h2>Course Outcome {idx}</h2>
                <div class="co-description">CO{idx}: {co}</div>
            </div>
"""
            
            # Program Outcomes
            if po:
                html += """
            <div class="po-section">
                <h3>Program Outcomes (PO)</h3>
                <ul>
"""
                if isinstance(po, list):
                    for po_item in po:
                        html += f"                    <li>{po_item}</li>\n"
                else:
                    html += f"                    <li>{po}</li>\n"
                html += """                </ul>
            </div>
"""
            
            # Topics
            if topics:
                html += """
            <div class="topics-section">
                <h3>Topics Covered</h3>
                <ul>
"""
                for topic in topics:
                    html += f"                    <li>{topic}</li>\n"
                html += """                </ul>
            </div>
"""
            
            # Questions
            if co_questions:
                html += f"""
            <div class="questions-section">
                <div class="questions-header">Questions (Total: {len(co_questions)})</div>
"""
                for q_idx, question in enumerate(co_questions, 1):
                    html += f"""
                <div class="question">
                    <span class="question-number">Q{idx}.{q_idx}.</span>
                    <span class="question-text">{question}</span>
                </div>
"""
                html += """
            </div>
"""
            
            html += """
        </div>
"""
        
        # Footer
        html += f"""
        <div class="footer">
            <p>End of Question Paper</p>
            <p>Generated by ScoriX Question Paper Generator</p>
        </div>
    </div>
</body>
</html>
"""
        
        return html
    
    def format_to_markdown(self, data: List[Any], course_name: str = "Course") -> str:
        """Format JSON data to Markdown format"""
        output = []
        now = datetime.now()
        
        # Header
        output.append("# Question Paper\n\n")
        output.append("**Generated by ScoriX AI System**\n\n")
        output.append(f"- **Date:** {now.strftime('%B %d, %Y')}\n")
        output.append(f"- **Time:** {now.strftime('%I:%M %p')}\n\n")
        output.append(f"## Course: {course_name}\n\n")
        output.append("---\n\n")
        
        # Extract questions
        if isinstance(data, (list, tuple)) and len(data) == 2:
            content_data, questions = data
        else:
            questions = data if isinstance(data, list) else []
        
        # Format each CO
        for idx, co_data in enumerate(questions, 1):
            if not isinstance(co_data, dict):
                continue
                
            co = co_data.get('CO', co_data.get('co', 'Unknown'))
            po = co_data.get('PO', co_data.get('po', []))
            topics = co_data.get('topics', [])
            co_questions = co_data.get('questions', [])
            
            output.append(f"## Course Outcome {idx}\n\n")
            output.append(f"**CO{idx}:** {co}\n\n")
            
            if po:
                output.append("### Program Outcomes (PO)\n\n")
                if isinstance(po, list):
                    for po_item in po:
                        output.append(f"- {po_item}\n")
                else:
                    output.append(f"- {po}\n")
                output.append("\n")
            
            if topics:
                output.append("### Topics Covered\n\n")
                for topic in topics:
                    output.append(f"- {topic}\n")
                output.append("\n")
            
            if co_questions:
                output.append(f"### Questions (Total: {len(co_questions)})\n\n")
                for q_idx, question in enumerate(co_questions, 1):
                    output.append(f"**Q{idx}.{q_idx}.** {question}\n\n")
            
            output.append("---\n\n")
        
        output.append("\n**End of Question Paper**\n")
        
        return ''.join(output)


if __name__ == "__main__":
    # Example usage
    formatter = QuestionPaperFormatter()
    
    # Load sample data
    import sys
    if len(sys.argv) > 1:
        with open(sys.argv[1], 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        course_name = sys.argv[2] if len(sys.argv) > 2 else "Programming Fundamentals"
        
        # Generate formatted outputs
        print("Generating formatted question papers...")
        
        # Text format
        text_output = formatter.format_to_text(data, course_name)
        with open('formatted_question_paper.txt', 'w', encoding='utf-8') as f:
            f.write(text_output)
        print("✓ Text format saved to: formatted_question_paper.txt")
        
        # HTML format
        html_output = formatter.format_to_html(data, course_name)
        with open('formatted_question_paper.html', 'w', encoding='utf-8') as f:
            f.write(html_output)
        print("✓ HTML format saved to: formatted_question_paper.html")
        
        # Markdown format
        md_output = formatter.format_to_markdown(data, course_name)
        with open('formatted_question_paper.md', 'w', encoding='utf-8') as f:
            f.write(md_output)
        print("✓ Markdown format saved to: formatted_question_paper.md")
    else:
        print("Usage: python question_paper_formatter.py <json_file> [course_name]")
